name       : python-srt
version    : 3.5.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/18/a3/e1466f7c86a9e5d3e462ed6eb3a548917e93cc1ee212cd927f8f4e887ae9/srt-3.5.2.tar.gz : 7aa4ad5ce4126d3f53b3e7bc4edaa86653d0378bf1c0b1ab8c59f5ab41384450
license    : MIT
component  : programming.python
summary    : A tiny but featureful Python library for parsing, modifying, and composing SRT files.
description: |
    A tiny but featureful Python library for parsing, modifying, and composing SRT files.
replaces  :
    - python-pysrt
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test